export const workflowStages = [
  'Land Identified',
  'Title Verification',
  'Encumbrance Check',
  'Legal Review',
  'Approval',
  'Acquisition Completed',
];

export const initialLandRecords = [
  {
    id: 'LR-1001',
    surveyNumber: 'SY-42/18',
    parcelId: 'CR-PCL-001',
    location: 'North Industrial Corridor',
    village: 'Madhavaram',
    district: 'Chennai',
    state: 'Tamil Nadu',
    area: 18.4,
    ownerName: 'Ramanathan Estates',
    contactNumber: '9840012345',
    address: '12 Lake View Road, Chennai',
    titleStatus: 'Pending',
    encumbranceStatus: 'Clear',
    legalClearanceStatus: 'In Review',
    remarks: 'Revenue record mutation pending.',
    workflowStage: 2,
    createdAt: '2026-01-12',
  },
  {
    id: 'LR-1002',
    surveyNumber: 'SY-75/03',
    parcelId: 'CR-PCL-002',
    location: 'Eastern Logistics Zone',
    village: 'Ponneri',
    district: 'Tiruvallur',
    state: 'Tamil Nadu',
    area: 26.7,
    ownerName: 'S. Meenakshi',
    contactNumber: '9876543210',
    address: '44 Market Street, Ponneri',
    titleStatus: 'Verified',
    encumbranceStatus: 'Issue Found',
    legalClearanceStatus: 'Pending',
    remarks: 'Historical mortgage entry requires release deed review.',
    workflowStage: 3,
    createdAt: '2026-02-08',
  },
  {
    id: 'LR-1003',
    surveyNumber: 'SY-19/11',
    parcelId: 'CR-PCL-003',
    location: 'Greenfield Assembly Cluster',
    village: 'Sriperumbudur',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    area: 12.1,
    ownerName: 'Kaveri Agro Holdings',
    contactNumber: '9003123456',
    address: '8 Industrial Estate Road, Sriperumbudur',
    titleStatus: 'Verified',
    encumbranceStatus: 'Clear',
    legalClearanceStatus: 'Cleared',
    remarks: 'Ready for acquisition closure.',
    workflowStage: 6,
    createdAt: '2026-03-19',
  },
  {
    id: 'LR-1004',
    surveyNumber: 'SY-108/22',
    parcelId: 'CR-PCL-004',
    location: 'Southern Expansion Belt',
    village: 'Oragadam',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    area: 31.5,
    ownerName: 'Vetrivel Family Trust',
    contactNumber: '9444412121',
    address: '102 GST Road, Chennai',
    titleStatus: 'Rejected',
    encumbranceStatus: 'Issue Found',
    legalClearanceStatus: 'Blocked',
    remarks: 'Boundary dispute noted in preliminary review.',
    workflowStage: 4,
    createdAt: '2026-04-03',
  },
  {
    id: 'LR-1005',
    surveyNumber: 'SY-63/09',
    parcelId: 'CR-PCL-005',
    location: 'Western Utility Corridor',
    village: 'Avadi',
    district: 'Tiruvallur',
    state: 'Tamil Nadu',
    area: 9.8,
    ownerName: 'Nila Infrastructure Pvt Ltd',
    contactNumber: '9888899990',
    address: '21 Corporate Avenue, Chennai',
    titleStatus: 'Pending',
    encumbranceStatus: 'Pending',
    legalClearanceStatus: 'Pending',
    remarks: 'Awaiting owner document bundle.',
    workflowStage: 1,
    createdAt: '2026-05-14',
  },
];

export const recentActivities = [
  'Legal clearance completed for SY-19/11',
  'Encumbrance issue escalated for SY-75/03',
  'Title verification assigned for SY-42/18',
  'New parcel added in Western Utility Corridor',
  'Boundary dispute note updated for SY-108/22',
];
